"""Utworzenie tabeli zadan

Revision ID: fb2a817ff693
Revises: 
Create Date: 2026-05-19 13:27:56.407563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb2a817ff693'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zadania',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opis', sa.String(), nullable=False),
    sa.Column('zrobione', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zadania')
    # ### end Alembic commands ###
